### ISSUE TITLE
SSH config parse error with global parameters

### ISSUE THREAD

**Issue by Shr3ps** [quantumsheep/sshs#31]
```bash
 %  sshs                                                                                                                         
2022/06/14 17:48:46 /home/shreps/.ssh/config:0: config variable before Host variable
```

```bash
%  head .ssh/config                                                                                                                                                                              
AddressFamily inet

Host bitbucket.org
    Hostname bitbucket.org
    User git
    ControlMaster no

Host github.com
    StrictHostKeyChecking no
    User git
```

sshs seems not understand / don't ignore the `AddressFamily` parameter in my ssh config file.

**Comment by sgaunet** [comment]
Agree with Sh3ps, I have the directive : ForwardAgent yes 
And same error :)

**Comment by antoine-em** [comment]
I had the same issue as mentioned here and had to comment the global directive `ServerAliveInterval 10` I defined in my `~/.ssh/config` file to make it work.

Is there some workaround to make those global config elements to be taken into account in another way or is it a bug/limitation in the current design of sshs ?

Thanks for this great tool ✨ otherwise, happy I could find it from korben's website ;)

**Comment by quantumsheep** [comment]
It needs to be implemented in [mikkeloscar/sshconfig](https://github.com/mikkeloscar/sshconfig). As things continues it seems more clever to rewrite it entirely as it doesn't support a lot of features.

**Comment by quantumsheep** [comment]
Hey! There is now a custom ssh config parser in 4.0.0, give it a try!
