### ISSUE TITLE
Hostname and Aliases are the same

### ISSUE THREAD

**Issue by vecinohk** [quantumsheep/sshs#49]
Hostname and Aliases are the same - the same data are displayed twice. Could it be removed please?

`Hostname         │ Aliases            │ User │ Target              │ Port │ `

```
sshs version 3.4.0
https://aur.archlinux.org/packages/sshs

ssh -V
OpenSSH_9.1p1, OpenSSL 3.0.7 1 Nov 2022
```

Thanks

**Comment by sabbath88** [comment]
It works the same for me as it does for you. 
I thought you could use the column aliases for "grouping". In my case I have over 50 defined connections to let's call it 5 datacenter. So each of the 10 connections could have an alias, e.g. datacenter2, etc. In this way, when looking for a connection (without knowing the exact host name), I could search for all hosts for a given datacenter2 and using the down arrow key to reach what I am interested in. 
The problem is that I don't know how to set up aliases :)

**Comment by vecinohk** [comment]
@sabbath88 Hi, I don't know what you mean. Could you show me your sample config? Thanks!

**Comment by vecinohk** [comment]
@quantumsheep Hi, do you have any tips please?

**Comment by bodhisensei** [comment]
hello same problem, Hostname and Aliases are the same.
How to customize ? Thx you
see example of  config file:

Host TOTO
  Hostname toto.example.com
  User votre_nom_utilisateur_toto
  Port 22
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa

**Comment by quantumsheep** [comment]
Hey! That should not be a problem anymore in 4.0.0
